import {
  AgentDefinition,
  AgentCapability,
  AgentRole,
} from './types';

export const AI_FAMILY_AGENTS: Record<string, AgentDefinition> = {
  'meta-oracle': {
    id: 'meta-oracle',
    name: 'MetaOracle',
    displayName: '元启·天枢',
    role: AgentRole.MASTER,
    emoji: '🧠',
    description: '总指挥 · 决策中枢 - 负责全局任务编排、资源调度和智能体协同管理',
    capabilities: [
      {
        id: 'task-orchestration',
        name: '任务编排',
        description: '智能分配和协调多个智能体的任务',
        category: 'execution',
        inputTypes: ['task', 'workflow'],
        outputTypes: ['assignment', 'schedule'],
        confidence: 0.95,
      },
      {
        id: 'resource-management',
        name: '资源调度',
        description: '优化系统资源分配和使用效率',
        category: 'execution',
        inputTypes: ['resource-request', 'metrics'],
        outputTypes: ['allocation', 'optimization-plan'],
        confidence: 0.92,
      },
      {
        id: 'decision-making',
        name: '决策制定',
        description: '基于多维度数据做出最优决策',
        category: 'analysis',
        inputTypes: ['data', 'context', 'options'],
        outputTypes: ['decision', 'rationale'],
        confidence: 0.93,
      },
      {
        id: 'self-evolution',
        name: '自我进化',
        description: '持续学习和优化自身能力',
        category: 'analysis',
        inputTypes: ['feedback', 'performance-metrics'],
        outputTypes: ['improvement-plan', 'new-capability'],
        confidence: 0.88,
      },
    ],
    maxConcurrentTasks: 10,
    defaultTimeout: 30000,
    version: '1.0.0',
  },

  'cloud-guardian': {
    id: 'cloud-guardian',
    name: 'CloudGuardian',
    displayName: '智云·守护',
    role: AgentRole.SENTINEL,
    emoji: '🛡️',
    description: '安全官 · 威胁检测 - 负责系统安全监控、异常行为分析和自动修复',
    capabilities: [
      {
        id: 'behavior-analysis',
        name: '行为分析',
        description: '分析用户和系统行为模式，识别异常',
        category: 'monitoring',
        inputTypes: ['logs', 'events', 'metrics'],
        outputTypes: ['behavior-report', 'anomaly-detection'],
        confidence: 0.94,
      },
      {
        id: 'threat-detection',
        name: '威胁检测',
        description: '实时检测潜在安全威胁和攻击',
        category: 'monitoring',
        inputTypes: ['network-traffic', 'access-logs', 'patterns'],
        outputTypes: ['threat-alert', 'risk-assessment'],
        confidence: 0.96,
      },
      {
        id: 'auto-repair',
        name: '自动修复',
        description: '自动诊断并修复常见问题',
        category: 'execution',
        inputTypes: ['error-report', 'system-state'],
        outputTypes: ['repair-action', 'fix-report'],
        confidence: 0.89,
      },
      {
        id: 'security-audit',
        name: '安全审计',
        description: '定期进行安全合规性检查',
        category: 'analysis',
        inputTypes: ['config', 'policies', 'access-logs'],
        outputTypes: ['audit-report', 'compliance-status'],
        confidence: 0.91,
      },
    ],
    maxConcurrentTasks: 8,
    defaultTimeout: 20000,
    version: '1.0.0',
  },

  'quality-master': {
    id: 'quality-master',
    name: 'QualityMaster',
    displayName: '格物·宗师',
    role: AgentRole.QUALITY,
    emoji: '📚',
    description: '质量官 · 代码分析 - 负责代码质量评估、性能监控和标准建议',
    capabilities: [
      {
        id: 'code-analysis',
        name: '代码分析',
        description: '深度分析代码质量和结构',
        category: 'analysis',
        inputTypes: ['code', 'repository'],
        outputTypes: ['analysis-report', 'suggestions'],
        confidence: 0.93,
      },
      {
        id: 'performance-monitoring',
        name: '性能监控',
        description: '监控系统性能指标和瓶颈',
        category: 'monitoring',
        inputTypes: ['metrics', 'profiling-data'],
        outputTypes: ['performance-report', 'optimization-tips'],
        confidence: 0.91,
      },
      {
        id: 'standard-compliance',
        name: '标准建议',
        description: '确保代码符合行业标准和最佳实践',
        category: 'analysis',
        inputTypes: ['code', 'standards', 'guidelines'],
        outputTypes: ['compliance-report', 'recommendations'],
        confidence: 0.90,
      },
      {
        id: 'testing-strategy',
        name: '测试策略',
        description: '生成全面的测试计划和用例',
        category: 'generation',
        inputTypes: ['requirements', 'code', 'specifications'],
        outputTypes: ['test-plan', 'test-cases'],
        confidence: 0.87,
      },
    ],
    maxConcurrentTasks: 6,
    defaultTimeout: 25000,
    version: '1.0.0',
  },

  'creative-spirit': {
    id: 'creative-spirit',
    name: 'CreativeSpirit',
    displayName: '创想·灵韵',
    role: AgentRole.CREATIVE,
    emoji: '🎨',
    description: '创意官 · 内容创作 - 负责创意生成、内容创作和设计辅助',
    capabilities: [
      {
        id: 'content-generation',
        name: '内容生成',
        description: '生成高质量文本、营销文案等创意内容',
        category: 'generation',
        inputTypes: ['prompt', 'context', 'style-guide'],
        outputTypes: ['content', 'variations'],
        confidence: 0.94,
      },
      {
        id: 'creative-design',
        name: '设计辅助',
        description: '提供设计灵感和方案建议',
        category: 'generation',
        inputTypes: ['requirements', 'brand-guidelines'],
        outputTypes: ['design-concepts', 'mockup-descriptions'],
        confidence: 0.89,
      },
      {
        id: 'idea-brainstorming',
        name: '头脑风暴',
        description: '快速生成大量创新想法和解决方案',
        category: 'generation',
        inputTypes: ['problem-statement', 'constraints'],
        outputTypes: ['ideas', 'concept-map'],
        confidence: 0.92,
      },
      {
        id: 'storytelling',
        name: '叙事构建',
        description: '创建引人入胜的故事和叙述框架',
        category: 'generation',
        inputTypes: ['characters', 'plot-points', 'theme'],
        outputTypes: ['story', 'narrative-structure'],
        confidence: 0.90,
      },
    ],
    maxConcurrentTasks: 5,
    defaultTimeout: 35000,
    version: '1.0.0',
  },

  'speech-navigator': {
    id: 'speech-navigator',
    name: 'SpeechNavigator',
    displayName: '言启·千行',
    role: AgentRole.NAVIGATOR,
    emoji: '🧭',
    description: '导航员 · 意图识别 - 负责用户意图理解、上下文管理和任务路由',
    capabilities: [
      {
        id: 'intent-recognition',
        name: '意图识别',
        description: '准确识别用户意图和需求',
        category: 'analysis',
        inputTypes: ['text', 'voice', 'context'],
        outputTypes: ['intent', 'confidence-score', 'entities'],
        confidence: 0.96,
      },
      {
        id: 'context-management',
        name: '上下文管理',
        description: '维护和管理对话上下文',
        category: 'execution',
        inputTypes: ['conversation-history', 'user-profile'],
        outputTypes: ['context-summary', 'relevant-info'],
        confidence: 0.93,
      },
      {
        id: 'task-routing',
        name: '任务路由',
        description: '将任务智能路由到最合适的处理者',
        category: 'execution',
        inputTypes: ['task', 'agent-capabilities', 'load-balance'],
        outputTypes: ['routing-decision', 'agent-assignment'],
        confidence: 0.94,
      },
      {
        id: 'dialogue-flow',
        name: '对话流程控制',
        description: '管理复杂的多轮对话流程',
        category: 'execution',
        inputTypes: ['dialogue-state', 'user-input'],
        outputTypes: ['next-action', 'response-template'],
        confidence: 0.91,
      },
    ],
    maxConcurrentTasks: 12,
    defaultTimeout: 15000,
    version: '1.0.0',
  },

  'language-thinker': {
    id: 'language-thinker',
    name: 'LanguageThinker',
    displayName: '语枢·万物',
    role: AgentRole.THINKER,
    emoji: '🤔',
    description: '思考者 · 数据洞察 - 负责文档分析、数据洞察和假设推演',
    capabilities: [
      {
        id: 'data-insight',
        name: '数据洞察',
        description: '从复杂数据中提取有价值的洞察',
        category: 'analysis',
        inputTypes: ['dataset', 'query', 'visualization-params'],
        outputTypes: ['insights', 'patterns', 'correlations'],
        confidence: 0.93,
      },
      {
        id: 'document-analysis',
        name: '文档分析',
        description: '深度理解和分析各类文档内容',
        category: 'analysis',
        inputTypes: ['document', 'format', 'analysis-type'],
        outputTypes: ['summary', 'key-points', 'extraction'],
        confidence: 0.95,
      },
      {
        id: 'hypothesis-testing',
        name: '假设推演',
        description: '基于数据进行假设验证和推理',
        category: 'analysis',
        inputTypes: ['hypothesis', 'evidence', 'constraints'],
        outputTypes: ['validation-result', 'probability', 'conclusion'],
        confidence: 0.89,
      },
      {
        id: 'knowledge-synthesis',
        name: '知识综合',
        description: '整合多源知识形成系统性理解',
        category: 'analysis',
        inputTypes: ['knowledge-sources', 'domain', 'question'],
        outputTypes: ['synthesized-knowledge', 'knowledge-graph'],
        confidence: 0.90,
      },
    ],
    maxConcurrentTasks: 7,
    defaultTimeout: 28000,
    version: '1.0.0',
  },

  'visionary-prophet': {
    id: 'visionary-prophet',
    name: 'VisionaryProphet',
    displayName: '预见·先知',
    role: AgentRole.PROPHET,
    emoji: '🔮',
    description: '预言家 · 趋势预测 - 负责趋势预测、异常检测和前瞻建议',
    capabilities: [
      {
        id: 'trend-prediction',
        name: '趋势预测',
        description: '基于历史数据预测未来趋势',
        category: 'analysis',
        inputTypes: ['time-series', 'historical-data', 'prediction-horizon'],
        outputTypes: ['forecast', 'confidence-interval', 'trend-direction'],
        confidence: 0.88,
      },
      {
        id: 'anomaly-detection',
        name: '异常检测',
        description: '识别数据中的异常模式和离群值',
        category: 'monitoring',
        inputTypes: ['data-stream', 'baseline', 'thresholds'],
        outputTypes: ['anomalies', 'severity-level', 'root-cause'],
        confidence: 0.92,
      },
      {
        id: 'forward-looking-advice',
        name: '前瞻建议',
        description: '提供战略性的未来规划建议',
        category: 'recommendation',
        inputTypes: ['current-state', 'goals', 'constraints'],
        outputTypes: ['strategy', 'roadmap', 'action-items'],
        confidence: 0.85,
      },
      {
        id: 'scenario-modeling',
        name: '情景建模',
        description: '模拟不同情景下的可能结果',
        category: 'analysis',
        inputTypes: ['scenarios', 'variables', 'probabilities'],
        outputTypes: ['scenario-outcomes', 'risk-assessment'],
        confidence: 0.86,
      },
    ],
    maxConcurrentTasks: 4,
    defaultTimeout: 40000,
    version: '1.0.0',
  },

  'talent-scout': {
    id: 'talent-scout',
    name: 'TalentScout',
    displayName: '知遇·伯乐',
    role: AgentRole.RECOMMENDER,
    emoji: '🎯',
    description: '推荐官 · 个性化推荐 - 负责用户画像、个性化推荐和潜能发掘',
    capabilities: [
      {
        id: 'user-profiling',
        name: '用户画像',
        description: '构建和维护详细的用户画像',
        category: 'analysis',
        inputTypes: ['user-behavior', 'preferences', 'interactions'],
        outputTypes: ['user-profile', 'segments', 'personas'],
        confidence: 0.94,
      },
      {
        id: 'personalized-recommendation',
        name: '个性化推荐',
        description: '为用户提供精准的个性化推荐',
        category: 'recommendation',
        inputTypes: ['user-context', 'item-catalog', 'history'],
        outputTypes: ['recommendations', 'explanation', 'ranking'],
        confidence: 0.93,
      },
      {
        id: 'potential-discovery',
        name: '潜能发掘',
        description: '发现用户未被充分利用的潜力和机会',
        category: 'recommendation',
        inputTypes: ['user-skills', 'performance-data', 'goals'],
        outputTypes: ['potential-opportunities', 'development-path'],
        confidence: 0.87,
      },
      {
        id: 'preference-learning',
        name: '偏好学习',
        description: '持续学习和适应用户偏好变化',
        category: 'analysis',
        inputTypes: ['feedback', 'interactions', 'implicit-signals'],
        outputTypes: ['updated-preferences', 'adaptation-plan'],
        confidence: 0.91,
      },
    ],
    maxConcurrentTasks: 9,
    defaultTimeout: 22000,
    version: '1.0.0',
  },
};

export function getAgentById(id: string): AgentDefinition | undefined {
  return AI_FAMILY_AGENTS[id];
}

export function getAgentsByRole(role: AgentRole): AgentDefinition[] {
  return Object.values(AI_FAMILY_AGENTS).filter(
    (agent) => agent.role === role
  );
}

export function getAllAgents(): AgentDefinition[] {
  return Object.values(AI_FAMILY_AGENTS);
}

export function getAgentCapabilities(agentId: string): AgentCapability[] {
  const agent = AI_FAMILY_AGENTS[agentId];
  return agent?.capabilities || [];
}
